# 数据源配置
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sys_shiro?useUnicode=true&amp;characterEncoding=utf-8&amp;useSSL=false
    username: ENC(oupsvhAa7X5Y6yTiLPRdXA==)
    password: ENC(uzUhb69hJeCSJv4yiFz67g==)
    dbcp2:
      initial-size: 1
      min-idle: 1
      max-conn-lifetime-millis: 20

  mvc:
    favicon:
      enabled: false

  # 模板配置
  thymeleaf:
    # 这个开发配置为false，避免改了模板还要重启服务器
    cache: false
    # 配置为Legacy HTML5模式，还需要额外引入一个包用来处理代码
    mode: HTML
    # 这个是配置模板路径的，默认就是templates
    prefix: classpath:/templates/
    # 检查模板位置
    # check-template-location: true
    suffix: .html
    encoding: UTF-8
    # servlet:
      # content-type: text/html

  redis:
    host: localhost
    port: 6379
    password: 111111
    timeout: 0
    jedis:
      pool:
        # 连接池中的最大空闲连接
        max-idle: 8
        min-idle: 0
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1

mybatis-plus:
  # 如果是放在src/main/java目录下 classpath:/com/yourpackage/*/mapper/*Mapper.xml
  # 如果是放在resource目录 classpath:/mapper/*Mapper.xml
  mapper-locations: classpath:/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.pyq.entity
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 0
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: true
    #mp2.3+ 全局表前缀 mp_
    #table-prefix: mp_
    #刷新mapper 调试神器
    #refresh-mapper: true
    #数据库大写下划线转换
    #capital-mode: true
    # Sequence序列接口实现类配置
    key-generator: com.baomidou.mybatisplus.incrementer.OracleKeyGenerator
    #逻辑删除配置（下面3个配置）
    logic-delete-value: 1
    logic-not-delete-value: 0
    # sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
    #自定义填充策略接口实现
    # meta-object-handler: com.baomidou.springboot.MyMetaObjectHandler
    configuration:
      #配置返回数据库(column下划线命名&&返回java实体是驼峰命名)，自动匹配无需as（没开启这个，SQL需要写as： select user_id as userId）
      map-underscore-to-camel-case: true
      cache-enabled: false
      #配置JdbcTypeForNull, oracle数据库必须配置
      jdbc-type-for-null: 'null'

logging:
  config: classpath:logback-boot.xml

jasypt:
  encryptor:
    password: EbfYkitulv73I2p0mXI50JMXoaxZTKJ7